# Generated by Django 4.1.7 on 2023-03-24 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relapp', '0002_department_workers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
    ]
