# Generated by Django 4.1.7 on 2023-03-24 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relapp', '0003_alter_department_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empdep', to='relapp.department'),
        ),
    ]
