# Generated by Django 4.1.7 on 2023-03-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
