# Generated by Django 4.1.7 on 2023-03-20 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_release_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'get_latest_by': ['release_date'], 'ordering': ['title', 'director']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 12, 10, 30, 517393)),
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movie',
        ),
    ]
