# Generated by Django 4.1.7 on 2023-03-20 07:05

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_options_alter_movie_release_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'get_latest_by': ['-release_date'], 'ordering': ['title', 'director']},
        ),
        migrations.AlterModelManagers(
            name='movie',
            managers=[
                ('mvmgr', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 12, 35, 13, 863525)),
        ),
    ]
