# Generated by Django 4.1.7 on 2023-03-21 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_options_alter_movie_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration_mins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 11, 37, 49, 519399)),
        ),
    ]
